export interface Product {
    id: string;
    name: string;
    category: string;
    image: string;
    images?: string[]; // New property for multiple images
    price: string;
    description: string;
    features: string[];
    isNew?: boolean;
}

export const products: Product[] = [
    // Carving Series Items
    {
        id: "alice-beige",
        name: "Alice Beige",
        category: "Carving Series",
        image: "/Carving/ALICE BEIGE (1).png",
        images: ["/Carving/ALICE BEIGE (1).png", "/Carving/ALICE BEIGE (2).png"],
        price: "Contact for Price",
        description: "Soft beige tones with a unique carving finish that adds depth and texture to any space.",
        features: ["Carving Finish", "Soft Texture", "Elegant"],
        isNew: true,
    },
    {
        id: "alice-nero",
        name: "Alice Nero",
        category: "Carving Series",
        image: "/Carving/ALICE NERO (1).png",
        images: ["/Carving/ALICE NERO (1).png", "/Carving/ALICE NERO (2).png"],
        price: "Contact for Price",
        description: "Dramatic black carving tile with subtle texture for a bold, modern statement.",
        features: ["Carving Finish", "Dark Tones", "Modern"],
    },
    {
        id: "alice-white",
        name: "Alice White",
        category: "Carving Series",
        image: "/Carving/ALICE WHITE (1).png",
        images: ["/Carving/ALICE WHITE (1).png", "/Carving/ALICE WHITE (2).png"],
        price: "Contact for Price",
        description: "Pristine white with a delicate carving effect, perfect for creating bright and airy interiors.",
        features: ["Carving Finish", "Bright", "Minimalist"],
    },
    {
        id: "amphora-bianco",
        name: "Amphora Bianco",
        category: "Carving Series",
        image: "/Carving/AMPHORA BIANCO (1).png",
        images: ["/Carving/AMPHORA BIANCO (1).png", "/Carving/AMPHORA BIANCO (2).png"],
        price: "Contact for Price",
        description: "Classic bianco styling with the tactile advantage of a carving finish.",
        features: ["Carving Finish", "Classic Look", "Textured"],
    },
    {
        id: "amphora-brown",
        name: "Amphora Brown",
        category: "Carving Series",
        image: "/Carving/AMPHORA BROWN (1).png",
        images: ["/Carving/AMPHORA BROWN (1).png", "/Carving/AMPHORA BROWN (2).png"],
        price: "Contact for Price",
        description: "Rich brown hues with a carved texture that emphasizes the natural earthy feel.",
        features: ["Carving Finish", "Earthy Tones", "Warm"],
    },
    {
        id: "amphora-grey",
        name: "Amphora Grey",
        category: "Carving Series",
        image: "/Carving/AMPHORA GREY (1).png",
        images: ["/Carving/AMPHORA GREY (1).png", "/Carving/AMPHORA GREY (2).png"],
        price: "Contact for Price",
        description: "Sophisticated grey tones with a carving finish for a contemporary industrial look.",
        features: ["Carving Finish", "Grey Tones", "Industrial"],
        isNew: true,
    },
    {
        id: "antique-statuario",
        name: "Antique Statuario",
        category: "Carving Series",
        image: "/Carving/ANTIQUE STATUARIO (1).png",
        images: ["/Carving/ANTIQUE STATUARIO (1).png", "/Carving/ANTIQUE STATUARIO (2).png"],
        price: "Contact for Price",
        description: "The timeless beauty of Statuario marble reimagined with an 'antique' carving texture.",
        features: ["Carving Finish", "Marble Look", "Antique Style"],
    },
    {
        id: "aristo-grey",
        name: "Aristo Grey",
        category: "Carving Series",
        image: "/Carving/ARISTO GREY (1).png",
        images: ["/Carving/ARISTO GREY (1).png", "/Carving/ARISTO GREY (2).png"],
        price: "Contact for Price",
        description: "Aristocratic grey shades with fine carving details for a premium finish.",
        features: ["Carving Finish", "Premium", "Grey"],
    },
    {
        id: "ark-wood-gris",
        name: "Ark Wood Gris",
        category: "Carving Series",
        image: "/Carving/ARK WOOD GRIS (1).png",
        images: ["/Carving/ARK WOOD GRIS (1).png", "/Carving/ARK WOOD GRIS (2).png"],
        price: "Contact for Price",
        description: "A fusion of wood look and stone texture in a cool gris tone with carving effects.",
        features: ["Carving Finish", "Wood Look", "Gris"],
    },
    {
        id: "aroma-grey",
        name: "Aroma Grey",
        category: "Carving Series",
        image: "/Carving/AROMA GREY (1).png",
        images: ["/Carving/AROMA GREY (1).png", "/Carving/AROMA GREY (2).png"],
        price: "Contact for Price",
        description: "Subtle aroma grey with soft carving textures for a relaxing atmosphere.",
        features: ["Carving Finish", "Soft Grey", "Texture"],
    },
    // 3D Series Items
    {
        id: "astilia-multy",
        name: "Astilia Multy",
        category: "3D Series",
        image: "/3D/ASTILIA MULTY.png",
        images: ["/3D/ASTILIA MULTY.png", "/3D/ASTILIA MULTY (2).png"],
        price: "Contact for Price",
        description: "A stunning 3D design featuring dynamic geometric patterns with a natural stone texture.",
        features: ["3D Effect", "Textured Finish", "Premium Design"],
        isNew: true,
    },
    {
        id: "bamboo-white",
        name: "Bamboo White",
        category: "3D Series",
        image: "/3D/BAMBOO WHITE.png",
        images: ["/3D/BAMBOO WHITE.png", "/3D/BAMBOO WHITE (2).png"],
        price: "Contact for Price",
        description: "Elegant bamboo-inspired texture in a pristine white finish for modern interiors.",
        features: ["3D Effect", "Nature Inspired", "Bright Finish"],
        isNew: true,
    },
    {
        id: "chex-multi",
        name: "Chex Multi",
        category: "3D Series",
        image: "/3D/CHEX MULTI.png",
        images: ["/3D/CHEX MULTI.png", "/3D/CHEX MULTI (2).png"],
        price: "Contact for Price",
        description: "Bold multi-colored checkerboard pattern with depth and dimension.",
        features: ["3D Effect", "Geometric Pattern", "Vibrant"],
    },
    {
        id: "chex-white",
        name: "Chex White",
        category: "3D Series",
        image: "/3D/CHEX WHITE.png",
        images: ["/3D/CHEX WHITE.png", "/3D/CHEX WHITE (2).png"],
        price: "Contact for Price",
        description: "Subtle white-on-white checkered design for a sophisticated 3D wall feature.",
        features: ["3D Effect", "Minimalist", "Textured"],
    },
    {
        id: "elegence-flower",
        name: "Elegence Flower",
        category: "3D Series",
        image: "/3D/ELEGENCE FLOWER.png",
        images: ["/3D/ELEGENCE FLOWER.png", "/3D/ELEGENCE FLOWER (2).png"],
        price: "Contact for Price",
        description: "Intricate floral motifs raised in relief for a decorative artistic statement.",
        features: ["3D Effect", "Floral Design", "Artistic"],
        isNew: true,
    },
    {
        id: "glassian-brown",
        name: "Glassian Brown",
        category: "3D Series",
        image: "/3D/GLASSIAN BROWN.png",
        images: ["/3D/GLASSIAN BROWN.png", "/3D/GLASSIAN BROWN (2).png"],
        price: "Contact for Price",
        description: "Deep brown tones with 3D depth and distinct texture.",
        features: ["3D Effect", "Textured", "Rich Tone"],
    },
    {
        id: "glassian-grey",
        name: "Glassian Grey",
        category: "3D Series",
        image: "/3D/GLASSIAN GREY.png",
        images: ["/3D/GLASSIAN GREY.png", "/3D/GLASSIAN GREY (2).png"],
        price: "Contact for Price",
        description: "Modern grey tones with dimensionality and tactile finish.",
        features: ["3D Effect", "Textured", "Modern"],
    },
    {
        id: "qury-brown",
        name: "Qury Brown",
        category: "3D Series",
        image: "/3D/QURY BROWN.png",
        images: ["/3D/QURY BROWN.png", "/3D/QURY BROWN (2).png"],
        price: "Contact for Price",
        description: "Unique quarried stone look with 3D relief texture in warm brown shades.",
        features: ["3D Effect", "Stone Look", "Textured"],
    },
    // Glossy Series Items
    {
        id: "aleut-aqua",
        name: "Aleut Aqua",
        category: "Glossy Series",
        image: "/Glossy/ALEUT AQUA (1).png",
        images: ["/Glossy/ALEUT AQUA (1).png", "/Glossy/ALEUT AQUA (2).png"],
        price: "Contact for Price",
        description: "Serene aqua tones with a high-gloss finish, bringing a refreshing and spacious feel.",
        features: ["High Gloss Finish", "Aqua Tones", "Premium"],
        isNew: true,
    },
    {
        id: "bresino-natural",
        name: "Bresino Natural",
        category: "Glossy Series",
        image: "/Glossy/BRESINO NATURAL (1).png",
        images: ["/Glossy/BRESINO NATURAL (1).png", "/Glossy/BRESINO NATURAL (2).png"],
        price: "Contact for Price",
        description: "Natural stone aesthetics with a glossy sheen for a sophisticated, earthy look.",
        features: ["High Gloss Finish", "Natural Look", "Earthy"],
    },
    {
        id: "celestial-green",
        name: "Celestial Green",
        category: "Glossy Series",
        image: "/Glossy/CELESTIAL GREEN (1).png",
        images: ["/Glossy/CELESTIAL GREEN (1).png", "/Glossy/CELESTIAL GREEN (2).png"],
        price: "Contact for Price",
        description: "Vibrant celestial green with a reflective surface, perfect for feature walls.",
        features: ["High Gloss Finish", "Vibrant Color", "Modern"],
    },
    {
        id: "celestial-grey",
        name: "Celestial Grey",
        category: "Glossy Series",
        image: "/Glossy/CELESTIAL GREY (1).png",
        images: ["/Glossy/CELESTIAL GREY (1).png", "/Glossy/CELESTIAL GREY(2).png"],
        price: "Contact for Price",
        description: "A futuristic grey tone with high-gloss polish, ideal for contemporary spaces.",
        features: ["High Gloss Finish", "Modern Grey", "Sleek"],
    },
    {
        id: "crane-blue",
        name: "Crane Blue",
        category: "Glossy Series",
        image: "/Glossy/CRANE BLUE (1).png",
        images: ["/Glossy/CRANE BLUE (1).png", "/Glossy/CRANE BLUE (2).png"],
        price: "Contact for Price",
        description: "Deep blue hues with a glass-like finish, adding depth and luxury.",
        features: ["High Gloss Finish", "Deep Blue", "Luxury"],
    },
    {
        id: "crane-natural",
        name: "Crane Natural",
        category: "Glossy Series",
        image: "/Glossy/CRANE NATURAL (1).png",
        images: ["/Glossy/CRANE NATURAL (1).png", "/Glossy/CRANE NATURAL (2).png"],
        price: "Contact for Price",
        description: "Soft natural tones in a glossy finish for a bright and welcoming environment.",
        features: ["High Gloss Finish", "Neutral", "Bright"],
    },
    {
        id: "crysta-white",
        name: "Crysta White",
        category: "Glossy Series",
        image: "/Glossy/CRYSTA WHITE (1).png",
        images: ["/Glossy/CRYSTA WHITE (1).png", "/Glossy/CRYSTA WHITE (2).png"],
        price: "Contact for Price",
        description: "Pure crystalline white with a mirror-like gloss for ultimate elegance.",
        features: ["High Gloss Finish", "Pure White", "Elegant"],
    },
    // Golden Series Items
    {
        id: "alfre-aqua",
        name: "Alfre Aqua",
        category: "Golden Series",
        image: "/Golden/ALFRE AQUA.png",
        images: ["/Golden/ALFRE AQUA.png"],
        price: "Contact for Price",
        description: "Alfre Aqua adds a touch of refreshing elegance with its golden-infused aqua tones.",
        features: ["Golden Finish", "Aqua Tones", "Luxury"],
        isNew: true,
    },
    {
        id: "alfre-grey",
        name: "Alfre Grey",
        category: "Golden Series",
        image: "/Golden/ALFRE GREY.png",
        images: ["/Golden/ALFRE GREY.png"],
        price: "Contact for Price",
        description: "Sophisticated Alfre Grey tiles with golden accents for a modern luxury look.",
        features: ["Golden Finish", "Grey Tones", "Modern"],
    },
    {
        id: "aurora-azul",
        name: "Aurora Azul",
        category: "Golden Series",
        image: "/Golden/AURORA AZUL.png",
        images: ["/Golden/AURORA AZUL.png"],
        price: "Contact for Price",
        description: "Aurora Azul features a stunning blue palette enhanced by golden veins.",
        features: ["Golden Finish", "Blue Tones", "Premium"],
    },
    {
        id: "aurora-grey",
        name: "Aurora Grey",
        category: "Golden Series",
        image: "/Golden/AURORA GREY.png",
        images: ["/Golden/AURORA GREY.png"],
        price: "Contact for Price",
        description: "Elegant Aurora Grey tiles that blend soft grey with opulent golden details.",
        features: ["Golden Finish", "Grey Tones", "Elegant"],
    },
    {
        id: "echo-blue",
        name: "Echo Blue",
        category: "Golden Series",
        image: "/Golden/ECHO BLUE.png",
        images: ["/Golden/ECHO BLUE.png"],
        price: "Contact for Price",
        description: "Echo Blue captures the depth of the ocean with shimmering golden highlights.",
        features: ["Golden Finish", "Deep Blue", "Artistic"],
    },
    {
        id: "echo-grey",
        name: "Echo Grey",
        category: "Golden Series",
        image: "/Golden/ECHO GREY.png",
        images: ["/Golden/ECHO GREY.png"],
        price: "Contact for Price",
        description: "Subtle and refined, Echo Grey offers a neutral backdrop with golden sophistcation.",
        features: ["Golden Finish", "Neutral Grey", "Refined"],
    },
    {
        id: "elysian-gold",
        name: "Elysian Gold",
        category: "Golden Series",
        image: "/Golden/ELYSIAN GOLD.png",
        images: ["/Golden/ELYSIAN GOLD.png"],
        price: "Contact for Price",
        description: "Pure luxury defined, Elysian Gold makes a bold statement of wealth and style.",
        features: ["Golden Finish", "Gold Tones", "Opulent"],
        isNew: true,
    },
    {
        id: "midash-blue",
        name: "Midash Blue",
        category: "Golden Series",
        image: "/Golden/MIDASH BLUE.png",
        images: ["/Golden/MIDASH BLUE.png"],
        price: "Contact for Price",
        description: "Midash Blue combines royal blue with the Midas touch of gold.",
        features: ["Golden Finish", "Royal Blue", "Majestic"],
    },
    {
        id: "midash-green",
        name: "Midash Green",
        category: "Golden Series",
        image: "/Golden/MIDASH GREEN.png",
        images: ["/Golden/MIDASH GREEN.png"],
        price: "Contact for Price",
        description: "Midash Green brings nature's richness indoors with golden-green hues.",
        features: ["Golden Finish", "Green Tones", "Natural"],
    },
    {
        id: "midash-grey",
        name: "Midash Grey",
        category: "Golden Series",
        image: "/Golden/MIDASH GREY.png",
        images: ["/Golden/MIDASH GREY.png"],
        price: "Contact for Price",
        description: "The Midash Grey offers a sleek, metallic grey finish with hints of gold.",
        features: ["Golden Finish", "Metallic Grey", "Sleek"],
    },
    {
        id: "pearlux-aurum",
        name: "Pearlux Aurum",
        category: "Golden Series",
        image: "/Golden/PEARLUX AURUM.png",
        images: ["/Golden/PEARLUX AURUM.png"],
        price: "Contact for Price",
        description: "Pearlux Aurum shines with a pearlescent glow and distinct golden aura.",
        features: ["Golden Finish", "Pearlescent", "Radiant"],
    },
    {
        id: "pearlux",
        name: "Pearlux",
        category: "Golden Series",
        image: "/Golden/PEARLUX.png",
        images: ["/Golden/PEARLUX.png"],
        price: "Contact for Price",
        description: "Classic Pearlux design, marrying soft white tones with golden elegance.",
        features: ["Golden Finish", "White & Gold", "Classic"],
    },
    {
        id: "sunverde-aqua",
        name: "Sunverde Aqua",
        category: "Golden Series",
        image: "/Golden/SUNVERDE AQUA.png",
        images: ["/Golden/SUNVERDE AQUA.png"],
        price: "Contact for Price",
        description: "Sunverde Aqua reflects the sunlit sea, perfect for refreshing spaces.",
        features: ["Golden Finish", "Aqua", "Bright"],
    },
    // End of User Provided Items
];

export function getProduct(id: string) {
    return products.find((p) => p.id === id);
}
